version: '3.9'

volumes:
  db_data:

services:
  app:
    build: .
    volumes:
      - ./project:/usr/src/project
    ports:
      - "3000:3000"
    tty: true
    command: /bin/sh
  db:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=normal
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306